import Head from 'next/head'
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillPhone,
  AiFillMail
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Image from "next/image";
import hudson from "../public/hudson.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import web1 from "../public/easy-money-control.png";
import web2 from "../public/orangenotes.png";
import web3 from "../public/my-calculator.png";
import web4 from "../public/easycode.png";
import web5 from "../public/lab-design-system.png";
import web6 from "../public/react-f1.png";
import web7 from "../public/todo.png";
import web8 from "../public/crud-cadastro.png";
import web9 from "../public/cadastro-cep.png";
import web10 from "../public/conversor.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Hudson Santos - Portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen mb-20 ">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">hudson santos</h1>

            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>

              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="cv-hudson-santos.pdf"
                  download
                >
                  Baixar CV
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10 py-10 flex flex-col items-center">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Hudson Santos
            </h2>

            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Desenvolvedor Front-End
            </h3>

            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Programador focado em desenvolver aplicações web modernas. Arraste para baixo e conheça um pouco mais!
            </p>

            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/hudsonsamuelsantos" target="_blank" rel="noreferrer">
                <AiFillGithub />
              </a>

              <a href="https://www.linkedin.com/in/hudsonsamuelsantos/" target="_blank" rel="noreferrer">
                <AiFillLinkedin />
              </a>

              <a href="mailto:hudsnss@gmail.com" target="_blank" rel="noreferrer">
                <AiFillMail />
              </a>

              <a href="tel:+55031995053234">
                <AiFillPhone />
              </a>
            </div>
          </div>

          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-10 md:h-96 md:w-96 flex flex-col items-center">
            <Image src={hudson} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Sobre mim</h3>

            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Desde bem cedo, sempre tive paixão por tecnologias, sempre tive curiosidade de saber como elas funcionavam, e aprender como eram feitas.
            </p>

            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Embora tenha passado por áreas e experiências bem distintas na minha trajetória profissional, como por exemplo a área de Vendas, a área Industrial, e por 4 anos na área de Construção Civil,
              <span className="text-teal-500"> desde 2021 venho me desenvolvendo como programador</span>, e me aprimorando no Desenvolvimento Web, com o objetivo de realizar uma transição para esse área.
            </p>

            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              O Desenvolvimento Web une várias coisas que me chamam muita atenção e que realmente gosto, como o uso da criatividade e da inovação para
              <span className="text-teal-500"> resolver problemas reais por meio da tecnologia.</span>
            </p>
          </div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1 flex flex-col items-center" >
              <Image src={design} width={100} height={100} />

              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Front-End
              </h3>

              <p className="py-2">
                Desenvolvendo interfaces modernas, responsivas, e funcionais para apps e websites.
              </p>

              <h4 className="py-4 text-teal-600">Algumas ferramentas que eu uso</h4>

              <p className="text-gray-800 py-1">React.js</p>

              <p className="text-gray-800 py-1">Next.js</p>

              <p className="text-gray-800 py-1">Tailwind CSS</p>

              <p className="text-gray-800 py-1">Consumo de APIs</p>

              <p className="text-gray-800 py-1">Figma</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 flex flex-col items-center">
              <Image src={code} width={100} height={100} />

              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Back-End
              </h3>

              <p className="py-2">
                Desenvolvendo aplicações e APIs do lado do servidor, e integrando com bancos de dados.
              </p>

              <h4 className="py-4 text-teal-600">Algumas ferramentas que eu uso</h4>

              <p className="text-gray-800 py-1">Node.js</p>

              <p className="text-gray-800 py-1">Express</p>

              <p className="text-gray-800 py-1">MySQL</p>

              <p className="text-gray-800 py-1">MongoDB</p>

              <p className="text-gray-800 py-1">GraphQL</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 flex flex-col items-center">

              <Image src={consulting} width={100} height={100} />

              <h3 className="text-lg font-medium pt-8 pb-2 ">Outras Skills</h3>

              <p className="py-2">
                Buscando usar como programador todas soft skills que pude adquirir na minha trajetória profissional.
              </p>

              <h4 className="py-4 text-teal-600">Algumas das minhas competências</h4>

              <p className="text-gray-800 py-1">Experiência de trabalho em equipe</p>

              <p className="text-gray-800 py-1">Resolução de problemas</p>

              <p className="text-gray-800 py-1">Capacidade de adaptação</p>

              <p className="text-gray-800 py-1">Gestão de tempo</p>

              <p className="text-gray-800 py-1">Confiabilidade</p>
            </div>
          </div>
        </section>

        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portfólio</h3>

            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Desde de que comecei minha jornada como desenvolvedor sempre busquei criar
              <span className="text-teal-500"> meus projetos...</span>
            </p>

            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Veja abaixo alguns dos meus trabalhos!
            </p>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1" >
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />

              <h4 className="text-lg pt-4 leading-8 text-gray-800 dark:text-gray-200">
                Easy Money Control $
              </h4>

              <p className="text-md py-4 leading-8 text-gray-800 dark:text-gray-200">
                Um app de controle financeiro, para cadastrar e excluir transações, e ver o saldo de entrada e saída. Desenvolvido com
                <span className="text-teal-500"> Javascript, HTML5, e CSS3.</span>
              </p>

              <div className='flex justify-between'>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md"
                  href="https://hudsonsamuelsantos.github.io/easy-money-control"
                  target="_blank"
                  rel="noreferrer"
                >
                  Acessar o projeto
                </a>

                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://github.com/hudsonsamuelsantos/easy-money-control"
                  target="_blank"
                  rel="noreferrer"
                >
                  Ver o código
                </a>
              </div>
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />

              <h4 className="text-lg pt-4 leading-8 text-gray-800 dark:text-gray-200">
                OrangeNotes
              </h4>

              <p className="text-md py-4 leading-8 text-gray-800 dark:text-gray-200">
                Um app para guardar anotações de forma organizada e fácil de achar, além de fazer progresso subindo em níveis de gameficação. Desenvolvido com
                <span className="text-teal-500"> React.js, Firebase, e CSS Modules.</span>
              </p>

              <div className='flex justify-between'>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md"
                  href="https://orangenotes.vercel.app"
                  target="_blank"
                  rel="noreferrer"
                >
                  Acessar o projeto
                </a>

                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://github.com/hudsonsamuelsantos/orange-notes"
                  target="_blank"
                  rel="noreferrer"
                >
                  Ver o código
                </a>
              </div>
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />

              <h4 className="text-lg pt-4 leading-8 text-gray-800 dark:text-gray-200">
                my.Calculator
              </h4>

              <p className="text-md py-4 leading-8 text-gray-800 dark:text-gray-200">
                Uma calculadora construída com base no design da calculadora do macOS. <br />
                Desenvolvida com
                <span className="text-teal-500"> React.js.</span>
              </p>

              <div className='flex justify-between'>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md"
                  href="https://hudsonsamuelsantos.github.io/my-calculator-react/"
                  target="_blank"
                  rel="noreferrer"
                >
                  Acessar o projeto
                </a>

                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://github.com/hudsonsamuelsantos/my-calculator-react"
                  target="_blank"
                  rel="noreferrer"
                >
                  Ver o código
                </a>
              </div>
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />

              <h4 className="text-lg pt-4 leading-8 text-gray-800 dark:text-gray-200">
                EasyCode Landing Page
              </h4>

              <p className="text-md py-4 leading-8 text-gray-800 dark:text-gray-200">
                Uma landing page responsiva apresentando um app de educação em tecnologia! <br />
                Desenvolvida com
                <span className="text-teal-500"> Javascript, HTML5, e CSS3.</span>
              </p>

              <div className='flex justify-between'>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md"
                  href="https://hudsonsamuelsantos.github.io/easyCode---Landing-Page/"
                  target="_blank"
                  rel="noreferrer"
                >
                  Acessar o projeto
                </a>

                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://github.com/hudsonsamuelsantos/easyCode---Landing-Page"
                  target="_blank"
                  rel="noreferrer"
                >
                  Ver o código
                </a>
              </div>
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />

              <h4 className="text-lg pt-4 leading-8 text-gray-800 dark:text-gray-200">
                Lab Design System
              </h4>

              <p className="text-md py-4 leading-8 text-gray-800 dark:text-gray-200">
                Um design system prototipado, documentado, e aplicado ao desenvolvimento de uma tela de login. As ferramentas utilizadas foram
                <span className="text-teal-500"> Figma, Storybook, React.js, Vite, e Tailwind CSS.</span>
              </p>

              <div className='flex justify-between'>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md"
                  href="https://lab-design-system-rho.vercel.app/"
                  target="_blank"
                  rel="noreferrer"
                >
                  Acessar o projeto
                </a>

                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://github.com/hudsonsamuelsantos/lab-design-system"
                  target="_blank"
                  rel="noreferrer"
                >
                  Ver o código
                </a>
              </div>
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />

              <h4 className="text-lg pt-4 leading-8 text-gray-800 dark:text-gray-200">
                React F1
              </h4>

              <p className="text-md py-4 leading-8 text-gray-800 dark:text-gray-200">
                Um website construído que apresenta o cronograma e a classificação da Fórmula 1! O projeto conta com documentação do front-end! Foi utilizado
                <span className="text-teal-500"> Storybook, React.js, Vite, e CSS Modules.</span>
              </p>

              <div className='flex justify-between'>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md"
                  href="http://react-f1.vercel.app"
                  target="_blank"
                  rel="noreferrer"
                >
                  Acessar o projeto
                </a>

                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://github.com/hudsonsamuelsantos/react-f1"
                  target="_blank"
                  rel="noreferrer"
                >
                  Ver o código
                </a>
              </div>
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web7}
              />

              <h4 className="text-lg pt-4 leading-8 text-gray-800 dark:text-gray-200">
                React + TS Todo
              </h4>

              <p className="text-md py-4 leading-8 text-gray-800 dark:text-gray-200">
                Um app de lista de tarefas, onde é possível criar, visualizar, editar, e excluir tarefas. Desenvolvido com
                <span className="text-teal-500"> TypeScript, React.js, e Bootstrap Icons.</span>
              </p>

              <div className='flex justify-between'>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md"
                  href="http://todo-typescript-react.vercel.app/"
                  target="_blank"
                  rel="noreferrer"
                >
                  Acessar o projeto
                </a>

                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://github.com/hudsonsamuelsantos/todo-typescript-react"
                  target="_blank"
                  rel="noreferrer"
                >
                  Ver o código
                </a>
              </div>
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web8}
              />

              <h4 className="text-lg pt-4 leading-8 text-gray-800 dark:text-gray-200">
                Sistema de Cadastro - CRUD
              </h4>

              <p className="text-md py-4 leading-8 text-gray-800 dark:text-gray-200">
                Um CRUD para o gerenciamento de cadastro de clientes. <br />
                Desenvolvido com
                <span className="text-teal-500"> TypeScript, Next.js, React.js, e Tailwind CSS.</span>
              </p>

              <div className='flex justify-between'>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md"
                  href="https://crud-cadastro-next-typescript-tailwind.vercel.app/"
                  target="_blank"
                  rel="noreferrer"
                >
                  Acessar o projeto
                </a>

                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://github.com/hudsonsamuelsantos/crud-cadastro-next-typescript-tailwind"
                  target="_blank"
                  rel="noreferrer"
                >
                  Ver o código
                </a>
              </div>
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web9}
              />

              <h4 className="text-lg pt-4 leading-8 text-gray-800 dark:text-gray-200">
                Cadastro com Consumo de API
              </h4>

              <p className="text-md py-4 leading-8 text-gray-800 dark:text-gray-200">
                Uma webpage de cadastro de usuários, na qual os campos são preenchidos automaticamente via API quando o usuário informa o seu CEP. Desenvolvido com
                <span className="text-teal-500"> JavaScript, HTML5, e CSS3.</span>
              </p>

              <div className='flex justify-between'>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md"
                  href="https://hudsonsamuelsantos.github.io/cadastro-cep-api/"
                  target="_blank"
                  rel="noreferrer"
                >
                  Acessar o projeto
                </a>

                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://github.com/hudsonsamuelsantos/cadastro-cep-api"
                  target="_blank"
                  rel="noreferrer"
                >
                  Ver o código
                </a>
              </div>
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web10}
              />

              <h4 className="text-lg pt-4 leading-8 text-gray-800 dark:text-gray-200">
                Conversor de Moeda$ com Consumo de API
              </h4>

              <p className="text-md py-4 leading-8 text-gray-800 dark:text-gray-200">
                Um app responsivo que permite a conversão de várias moedas de acordo com a cotação atual atualizada vinda da API. Desenvolvido com
                <span className="text-teal-500"> React.js, Axios, React Toastify.</span>
              </p>

              <div className='flex justify-between'>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md"
                  href="https://hudsonsamuelsantos.github.io/conversor-de-moedas-react/"
                  target="_blank"
                  rel="noreferrer"
                >
                  Acessar o projeto
                </a>

                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://github.com/hudsonsamuelsantos/conversor-de-moedas-react"
                  target="_blank"
                  rel="noreferrer"
                >
                  Ver o código
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
